### PR TITLE
Fixes for Travis CI

### PR DESCRIPTION
**Pull request by KL-7**

### CODE REVIEW

**Comment by jakl** [comment]
lgtm

**Comment by KL-7** [comment]
There're still a few Unicode related tests that fail on 1.8.7 – https://travis-ci.org/twitter/twitter-text-rb/jobs/16625131 :( I'll see if I can find a quick fix for them.

**Comment by KL-7** [comment]
TODO: upgrade to the latest conformance tests suit once twitter/twitter-text-conformance#67 is merged to fix CI build.

**Comment by caniszczyk** [comment]
Almost done @KL-7 ?

**Comment by KL-7** [comment]
@caniszczyk yeah, it's getting closer. There're still a few Unicode-related issues when running on Ruby 1.8.7, will investigate it in the next few days.

**Comment by jakl** [comment]
Shipit

**Comment by caniszczyk** [comment]
Thanks for doing this :hamster:

**Pull request merged**
